#!/usr/bin/env bash
set -e

LAMINAR_CFG=/home/chris/System/Laminar

# Create cfg for Laminar. We want this to survive garbage collection, so we keep
# the 'result' symlink as a GC root.
D=$(nix-build --show-trace -o "$(dirname "$0")/result")

# Atomically replace the cfg symlink to point to "$D" by creating a symlink with
# the same name in /tmp then moving it into the parent directory. This avoids
# nesting that we'd get from 'ln -s "$D" "$LAMINAR_CFG"' (e.g. ending up with
# /var/lib/laminar/cfg/cfg).
NAME=$(basename "$LAMINAR_CFG")
 DIR=$(dirname  "$LAMINAR_CFG")

rm -f /tmp/"$NAME"
ln -s "$D" /tmp/"$NAME"
mv -v /tmp/"$NAME" "$DIR"/
